---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: yy-os

description: Testing

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia-open
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /              

  - type: rpm-ostree
    install:
      - samba-dcerpc
      - samba-ldb-ldap-modules
      - samba-winbind-clients
      - samba-winbind-modules
      - samba
      - setools-console
      - sssd-ad
      - sssd-krb5
      - sssd-nfs-idmap
      - krb5-workstation
      - adcli
      - firewall-config
      - fuse-encfs
      - git-credential-libsecret
      - glow
      - gum
      - libxcrypt-compat
      - libsss_autofs
      - oddjob-mkhomedir
      - rclone
      - restic
      - wl-clipboard
      - cryfs
      - bcc
      - bpftop
      - bpftrace
      - cockpit-bridge
      - cockpit-machines
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
      - code
      - iotop
      - nicstat
      - numactl
      - p7zip-plugins
      - p7zip
      - rocm-hip
      - rocm-opencl
      - rocm-smi
      - sysprof
      - tiptop
      - trace-cmd
      - ydotool

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - com.mattjakeman.ExtensionManager
        - com.github.Matoking.protontricks
        - io.github.fastrizwaan.WineZGUI
        - io.github.dvlv.boxbuddyrs
        - it.mijorus.gearlever
        - com.github.tchx84.Flatseal
        - io.github.flattool.Warehouse
        - io.github.flattool.Ignition
        - io.missioncenter.MissionCenter
        - com.vysp3r.ProtonPlus
        - org.gnome.Calculator
        - org.gnome.Characters
        - org.gnome.Contacts
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.TextEditor
        - org.gnome.baobab
        - org.gnome.font-viewer
        - io.github.nokse22.Exhibit
        - de.leopoldluley.Clapgrep

  - type: copy
    src: files/system/etc/bluebuild/default-flatpaks/system/install
    dest: /etc/bluebuild/default-flatpaks/system/install

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
